title: DATA ANALYSIS IF NFL COMBINE AND LEAUGE DATA
description: The objective for my project is to determine whether a NFL player's success in the league has any correlation to their success in the combine.
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0
